services:
  frontend:
    build:
      context: ../
      dockerfile: docker/frontend/Dockerfile
    environment:
      - REACT_APP_BASE_URL=http://localhost:1236
    depends_on:
      - backend
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    networks:
      - base
  backend:
    build:
      context: ../
      dockerfile: docker/backend/Dockerfile
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - NVIDIA_VISIBLE_DEVICES=all
      - BACKEND_DATA_SOURCE=csv
      - BACKEND_CHROMADB_PATH=./data/chromadb
      - BACKEND_CHROMADB_COLLECTION_NAME=np2024-dataset
      - BACKEND_DATA_SOURCE_PATH=./data/202407251532-pandas-cleaned.csv
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia
    ports:
      - 1236:1236
    networks:
      - base
networks:
  base:
    driver: bridge
