version: '3.8'

services:
  frontend:
    build:
      context: ../
      dockerfile: docker/frontend/Dockerfile
    environment:
      - REACT_APP_BASE_URL=http://deeplearn01.advaoptical.com:1236
      - REACT_APP_WEBSOCKET_URL=ws://deeplearn01.advaoptical.com:1236
    depends_on:
      - backend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    networks:
      - base

  backend:
    build:
      context: ../
      dockerfile: docker/backend/Dockerfile
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia
    ports:
      - "1236:1236"
    volumes:
      - .semantic_search_cache/backend/data/models:/root/.cache/huggingface 
      - .semantic_search_cache/backend/data/chromadb:/app/data/chromadb
    networks:
      - base

networks:
  base:
    driver: bridge
